<?php
$categories = $this->getTwoLevelCategoties();
?>
<div>
<form>
	<div>
		<select id="brandselect">
			<option value="">Select Brand</option>
		</select>
	</div>
	<div>
		<select id="selectmodels">
			<option value="">Select Model</option>
		</select>
	</div>
	<div>
		<select id="selecttypes">
			<option value="">Select Type</option>
		</select>
	</div>
	<div id="div121">
		
	</div>
</form>
</div>
<script type="text/javascript">
	jQuery(function($){
        cats = <?php echo $categories; ?>;
		for (var i=0;i<cats.sub.length;++i)
		{
			$('#brandselect').append('<option value='+cats.sub[i].catid +'>'+cats.sub[i].name +'</options>');
		}
        $('#selectmodels').prop('disabled', true);
		$('#selecttypes').prop('disabled', true);

        $("#brandselect").change(function(e){
            $.ajax( {
		    url : "advsearch/index/getmodels/id/"+$("#brandselect").val(),
		    dataType : 'json',
		    data: $(this).serialize(),
		    success : function(data) {
		    	$('#selectmodels').prop('disabled', false);
		    	$('#selectmodels').find('option').remove().end().append('<option value="">Select Model</option>');
					for (var i=0;i<data.sub.length;++i)
					{
						$('#selectmodels').append('<option value='+data.sub[i].catid +'>'+data.sub[i].name +'</options>');
					}
		    	}
			});
        });


        $("#selectmodels").change(function(e){
            $.ajax( {
		    url : "advsearch/index/gettypes/id/"+$("#selectmodels").val(),
		    dataType : 'json',
		    data: $(this).serialize(),
		    success : function(data) {
		    	$('#selecttypes').prop('disabled', false);
		    	$('#selecttypes').find('option').remove().end().append('<option value="">Select Type</option>');
					for (var i=0;i<data.sub.length;++i)
					{
						$('#selecttypes').append('<option value='+data.sub[i].catid +' data-caturl='+data.sub[i].caturl+'>'+data.sub[i].name +'</options>');
					}
		    	}
			});
        });

		$("#selecttypes").change(function(e){
			$('#brandselect').prop('disabled', true);
			$('#selectmodels').prop('disabled', true);
			$('#selecttypes').prop('disabled', true);
            window.location = $(this).find(':selected').data("caturl");
        });


    });

</script>